### ISSUE TITLE
Player Product

### ISSUE THREAD

**Issue by felipefreitasnet** [bitaac/bitfabric#3]
How does item delivery to the player work?

The player went to the store, bought a certain product and the points were debited. What should the player do to receive the item?

Thanks!

**Comment by eklundkristoffer** [comment]
Hello!

For the item delivery to work you also need to implement some logics to your server. bitaac provides a global event out of the box, you can find it here: https://github.com/bitaac/bitaac/wiki/Shopsystem-LUA

**Comment by felipefreitasnet** [comment]
Amazing!

I'm going to use this script, thank you!
